# Generated by Django 5.1.4 on 2025-08-24 21:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RateCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=10)),
                ('quote', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('SWAP', 'SWAP'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('AUTO_SWAP', 'AUTO_SWAP')], max_length=20)),
                ('from_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('to_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('from_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('counterparty_wallet', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='payments.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'currency')},
            },
        ),
    ]
