# Generated by Django 5.1.4 on 2025-08-23 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='device',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
